const mongoose = require('mongoose');

const leagueSchema = mongoose.Schema({
  status: String,
  sport: String,
  season: String,
  season_type: String,
  name: String,
  draft_id: String,
  league_id: {
    type: String,
    required: true,
    unique: true,
  },
  previous_league_id: {
    type: String,
    required: false,
  },
  bracket_id: String,
  loser_bracket_id: String,
  settings: {
    playoff_type: Number,
    daily_waivers: Number,
    playoff_seed_type: Number,
    start_week: Number,
    divisions: Number,
    playoff_teams: Number,
    num_teams: Number,
  },
  total_rosters: Number,
  roster_positions: [String],
  scoring_settings: {
    blk_kick: Number,
    def_2pt: Number,
    def_kr_td: Number,
    def_pr_td: Number,
    def_st_ff: Number,
    def_st_fum_rec: Number,
    def_st_td: Number,
    def_td: Number,
    ff: Number,
    fgm_0_19: Number,
    fgm_20_29: Number,
    fgm_30_39: Number,
    fgm_40_49: Number,
    fgm_50p: Number,
    fgmiss_0_19: Number,
    fgmiss_20_29: Number,
    fgmiss: Number,
    fum_lost: Number,
    fum_rec: Number,
    fum: Number,
    int: Number,
    pass_2pt: Number,
    pass_int: Number,
    pass_td: Number,
    pass_yd: Number,
    pts_allow_0: Number,
    pts_allow_1_6: Number,
    pts_allow_14_20: Number,
    pts_allow_21_27: Number,
    pts_allow_28_34: Number,
    pts_allow_35p: Number,
    pts_allow_7_13: Number,
    rec_2pt: Number,
    rec_td: Number,
    rec_yd: Number,
    rec: Number,
    rush_2pt: Number,
    rush_td: Number,
    rush_yd: Number,
    sack: Number,
    safe: Number,
    st_ff: Number,
    st_fum_rec: Number,
    st_td: Number,
    xpm: Number,
    xpmiss: Number
  }
});

const League = module.exports = mongoose.model('leagues', leagueSchema);
